// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp_Multi_user_chat.Data;

#nullable disable

namespace WebApp_Multi_user_chat.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    [Migration("20241119233830_SecondMigration")]
    partial class SecondMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApp_Multi_user_chat.Entities.ChatHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<int>("ChatRoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("HistoryId");

                    b.HasIndex("ChatRoomId");

                    b.ToTable("ChatHistory");

                    b.HasData(
                        new
                        {
                            HistoryId = 1,
                            ChatRoomId = 1,
                            LastUpdated = new DateTime(2024, 11, 20, 2, 38, 27, 977, DateTimeKind.Local).AddTicks(678)
                        },
                        new
                        {
                            HistoryId = 2,
                            ChatRoomId = 2,
                            LastUpdated = new DateTime(2024, 11, 20, 2, 38, 27, 977, DateTimeKind.Local).AddTicks(681)
                        });
                });

            modelBuilder.Entity("WebApp_Multi_user_chat.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChatHistoryHistoryId")
                        .HasColumnType("int");

                    b.Property<int>("ChatRoomId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ChatHistoryHistoryId");

                    b.HasIndex("ChatRoomId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMessages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChatRoomId = 1,
                            Message = "Hello everyone!",
                            TimeStamp = new DateTime(2024, 11, 20, 2, 38, 27, 977, DateTimeKind.Local).AddTicks(716),
                            UserId = "user1"
                        },
                        new
                        {
                            Id = 2,
                            ChatRoomId = 1,
                            Message = "Good morning Alice!",
                            TimeStamp = new DateTime(2024, 11, 20, 2, 38, 27, 977, DateTimeKind.Local).AddTicks(719),
                            UserId = "user2"
                        },
                        new
                        {
                            Id = 3,
                            ChatRoomId = 2,
                            Message = "Who won the match yesterday?",
                            TimeStamp = new DateTime(2024, 11, 20, 2, 38, 27, 977, DateTimeKind.Local).AddTicks(722),
                            UserId = "user1"
                        });
                });

            modelBuilder.Entity("WebApp_Multi_user_chat.Entities.ChatRoom", b =>
                {
                    b.Property<int>("ChatRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatRoomId"));

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ChatRoomId");

                    b.ToTable("ChatRooms");

                    b.HasData(
                        new
                        {
                            ChatRoomId = 1,
                            LastUpdated = new DateTime(2024, 11, 20, 2, 38, 27, 977, DateTimeKind.Local).AddTicks(455),
                            RoomName = "General"
                        },
                        new
                        {
                            ChatRoomId = 2,
                            LastUpdated = new DateTime(2024, 11, 20, 2, 38, 27, 977, DateTimeKind.Local).AddTicks(481),
                            RoomName = "Sports"
                        });
                });

            modelBuilder.Entity("WebApp_Multi_user_chat.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationId");

                    b.ToTable("Notification");

                    b.HasData(
                        new
                        {
                            NotificationId = 1,
                            Message = "New user Alice joined the room",
                            NotificationType = "Join",
                            RoomName = "General",
                            TimeStamp = new DateTime(2024, 11, 20, 2, 38, 27, 977, DateTimeKind.Local).AddTicks(770),
                            UserId = "user1"
                        },
                        new
                        {
                            NotificationId = 2,
                            Message = "New user Bob joined the room",
                            NotificationType = "Join",
                            RoomName = "Sports",
                            TimeStamp = new DateTime(2024, 11, 20, 2, 38, 27, 977, DateTimeKind.Local).AddTicks(773),
                            UserId = "user2"
                        });
                });

            modelBuilder.Entity("WebApp_Multi_user_chat.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ChatRoomId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("ChatRoomId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = "user1",
                            Email = "alice@gmail.com",
                            Password = "password123",
                            UserName = "Alice"
                        },
                        new
                        {
                            UserId = "user2",
                            Email = "bob@gmail.com",
                            Password = "password456",
                            UserName = "Bob"
                        });
                });

            modelBuilder.Entity("WebApp_Multi_user_chat.Entities.ChatHistory", b =>
                {
                    b.HasOne("WebApp_Multi_user_chat.Entities.ChatRoom", "ChatRoom")
                        .WithMany()
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatRoom");
                });

            modelBuilder.Entity("WebApp_Multi_user_chat.Entities.ChatMessage", b =>
                {
                    b.HasOne("WebApp_Multi_user_chat.Entities.ChatHistory", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChatHistoryHistoryId");

                    b.HasOne("WebApp_Multi_user_chat.Entities.ChatRoom", "ChatRoom")
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp_Multi_user_chat.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApp_Multi_user_chat.Entities.User", b =>
                {
                    b.HasOne("WebApp_Multi_user_chat.Entities.ChatRoom", null)
                        .WithMany("Users")
                        .HasForeignKey("ChatRoomId");
                });

            modelBuilder.Entity("WebApp_Multi_user_chat.Entities.ChatHistory", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("WebApp_Multi_user_chat.Entities.ChatRoom", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
